### ISSUE TITLE
RHPDS - potential issue with 20+ user workshops

### ISSUE THREAD

**Issue by dudash** [RedHatGov/service-mesh-workshop-dashboard#15]
Collecting logs and failure info now

FYSA - @theckang

**Comment by dudash** [comment]
looks like running the Ansible playbooks to create an operator subscription sometimes creates multiple install plans for rh-sso (some of the users).

**Comment by dudash** [comment]
changes to fix this will be in the agnosticd repo

**Comment by andykrohg** [comment]
Relevant fix is here: https://github.com/andykrohg/agnosticd/commit/13996a5d5921b4005cc84a38dc4cf241f7a1b2fa#diff-6eb4cedead6d07cb7ab9b919f574c826b2ebfa7c4343595348cf975b8c8cbd63L46, though also including updates to pinned operator versions due to k8s API deprecations in deployments beyond OCP 4.6

**Comment by andykrohg** [comment]
Also uncovered a deprecated API in homeroom which prevented deployment in 4.9 and above. Should be fixed with: https://github.com/RedHatGov/workshop-spawner/commit/378ca3371f4f1cf1984aaa468dd996d95d1e6e15
