### ISSUE TITLE
Conflict of shortened resource CLI refs using `vs`

### ISSUE THREAD

**Issue by dudash** [RedHatGov/service-mesh-workshop-dashboard#16]
using `vs` for `virtualservice` conflicts with `volumesnapshots` and yields this error:

`Error from server (NotFound): volumesnapshots.snapshot.storage.k8s.io "userprofile" not found`

**Comment by dudash** [comment]
will be fixed in PR #18

**Comment by andykrohg** [comment]
Actually the one we need is this one... https://github.com/redhat-cop/agnosticd/pull/4683 `oops`

**Comment by andykrohg** [comment]
Done
